### ISSUE TITLE
Add an interrupt action

### ISSUE THREAD

**Issue by kekePower** [DecaTec/Nextcloud-Backup-Restore#11]
Hi.

Is it possible to add an interrupt action that will automatically go out of maintenance mode if a user hits Ctrl-C?

Thanks.

Cheers,
kekePower

**Comment by DecaTec** [comment]
Here you go: 802fec8

When the backup script gets cancelled, you user is asked if the maintenance mode should be enabled/disabled.

Keep in mind that a cancelled backup will not get deleted automatically.

**Comment by kekePower** [comment]
Thank you :-)
