### ISSUE TITLE
| instead of & in NextcloudRestore

### ISSUE THREAD

**Issue by sven-a** [DecaTec/Nextcloud-Backup-Restore#12]
tl;dr: in line 73 replace | with &

The number of parameters will always be not equal to one OR not equal to two. What you want is to check if the number is NOT (equal to one OR equal to two), so if you dissolve this bracket you get (NOT equal to one) AND (NOT equal to two).

**Comment by DecaTec** [comment]
Fixed with https://github.com/DecaTec/Nextcloud-Backup-Restore/commit/ef1ef85ac3afd35b16f402f4c35c860c99dc72e8

Thanks for the hint!
