### ISSUE TITLE
tipo on line 20

### ISSUE THREAD

**Issue by acatanyg** [DecaTec/Nextcloud-Backup-Restore#3]
NextcloudRestore.sh

currentRestoreDir="${mainBackupdir}/${restore}"
correct: currentRestoreDir="${mainBackupDir}/${restore}"

**Comment by DecaTec** [comment]
Resolved with https://github.com/DecaTec/Nextcloud-Backup-Restore/commit/374a1bc67f0cd848e46bf3cb685c9c7fa880f762
