### ISSUE TITLE
Question: Adjust keep maxNrOfBackups logic to keep of the last x days and then one per month

### ISSUE THREAD

**Issue by Chingato** [DecaTec/Nextcloud-Backup-Restore#5]
Hi,

is there a possibility to adjust the logic for keeping old backups?

> TODO:  The maximum number of backups to keep (when set to 0, all backups are kept)
> maxNrOfBackups=0

My requirements:
- I like to create daily backup files
- I like to keep all backup files of the last 7 days
- outside the 7 days I like to keep one file per month for the last xx month

-> as a result I would have the backups of the current week and then one per month for e.g. one year.

Any idea?

Thanks a lot.
Chingato

**Comment by DecaTec** [comment]
There's a very basic implementation of keeping/clean up of old backups in the scripts. Honestly, this was not the main intention of the scripts.
As you have to tailor the scripts for you installation/needs, you could also adjust the logic how backups are kept/cleaned up.
Another possibility would be to clean up old backups with a cron job running e.g. once a day.
