### ISSUE TITLE
Nextcloud ends up in installation mode after running the script

### ISSUE THREAD

**Issue by christiangrieger** [DecaTec/Nextcloud-Backup-Restore#8]
Hey there,

for some reason my Nextcloud ends up with a config with only a 'instanceid' => 'theinstanceid', left in it after the backup process.

Any idea why this happens?

System:
PHP 7.1.11
Apache
Latest Nextcloud 13.0.1

So looks like if it fails because no space left this happens :/

```
`Backup Nextcloud database...
mysqldump: Error: 'Disk full (/tmp/#sql_a3a_2.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")' when trying to dump tablespaces
mysqldump: Couldn't execute 'show fields from `oc_accounts`': Disk full (/tmp/#sql_a3a_0.MAI); waiting for someone to free some space... (errno: 28 "No space left on device") (1021)
Done

Starting web server...
Starting apache2 (via systemctl): apache2.service.
Done

Switching off maintenance mode...
Nextcloud is not installed - only a limited number of commands are available

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "maintenance:mode" is not defined.                      
  Did you mean this?                                              
      maintenance:install              `
```

Is there any way to get it to stop the script instead of activate the install mode on errors? :)

Greetings,
Chris

**Comment by DecaTec** [comment]
Hi,

the script only creates an archive from the NC files. So it should not change any files while the backup process.

Could you execute the commands one by one on the command line to see what's the single command leading to this error?

**Comment by christiangrieger** [comment]
I cant reproduce it only with no space left on device this happens when i try to disable nextcloud maintanance mode again. So i try to recode your code to delete backups first before make the next one maybe that helps me. Problem is that i just can store one backup because of the free space.
