### ISSUE TITLE
Backup to FTP-Server

### ISSUE THREAD

**Issue by terrar** [DecaTec/Nextcloud-Backup-Restore#9]
After using the backup i transfer it always to my FTP.
What do you think about implementing a feature to save the backups directly on an FTP-Server?
Is this possible to realize?

**Comment by DecaTec** [comment]
Hi,

of course this would be possible. But the only purpose of the script should be making backups. When adding an automated FTP upload, it would depent on the FTP upload. Next user wants handling of the backup files with rsync, WebDAV, SFTP, etc. 
Adding all these options (even commented out) would only blow up the backup script itself. So I don't think I would add all these options.

But you could easily add an FTP upload for a local copy of the script, see [here](https://serverfault.com/questions/279176/ftp-uploading-in-bash-script). Shouldn't be much work.
